name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main # или master
  pull_request:
    branches:
      - main # или master

jobs:
  build-and-test: # Мы объединяем build и test в одну задачу для простоты
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' # Устанавливаем конкретную версию Node.js

      - name: Install dependencies
        run: npm run install-deps # Выполняем наш скрипт из package.json

      - name: Run Build process
        run: npm run build # Выполняем наш скрипт сборки

      - name: Run Tests
        run: npm run test # Выполняем наш скрипт тестов

      - name: Check generated files (optional)
        run: | # Это многострочная команда
          ls -l dist/
          cat dist/index.html
